platform :ios, '12'
source 'https://cdn.cocoapods.org/'
install! 'cocoapods', :warn_for_unused_master_specs_repo => false
target 'SXPodCategory_Example' do
    pod 'SXPodCategory/Source', :path => '../'
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12'
      end
    end
  end
end
